const prefix='aria-portfolio:';
function bindEditable(el,key){el.textContent=localStorage.getItem(prefix+key)||el.textContent;el.addEventListener('click',e=>e.stopPropagation());el.addEventListener('input',()=>localStorage.setItem(prefix+key,el.textContent.trim()))}
function flipMarkup(id,label,compact=false){const copy=compact?'Click here and write the story behind this photograph.':'Write a short description: where you were, what caught your attention, and why this frame matters to you.';return `<div class="flip-inner"><div class="flip-face flip-front"><span class="placeholder-mark"><span>Image placeholder</span><span>${String(id).replace(/\D/g,'').slice(-2).padStart(2,'0')}</span></span></div><div class="flip-face flip-back"><strong>${label}</strong><p class="editable" contenteditable="true" data-edit-key="${id}">${copy}</p><span class="edit-hint">Click text to edit · saved on this device</span></div></div>`}
function activateFlips(root=document){root.querySelectorAll('.flip-card,.gallery-card').forEach(card=>{card.addEventListener('click',()=>card.classList.toggle('flipped'));card.querySelectorAll('[data-edit-key]').forEach(el=>bindEditable(el,el.dataset.editKey))})}
const featureGrid=document.querySelector('#feature-grid');if(featureGrid){for(let i=1;i<=8;i++){const card=document.createElement('article');card.className='flip-card';card.setAttribute('aria-label',`Selected photograph ${i}; click to flip`);card.innerHTML=flipMarkup(`selected-${i}`,`Frame ${String(i).padStart(2,'0')}`);featureGrid.appendChild(card)}activateFlips(featureGrid)}
document.querySelectorAll('.category-row').forEach(row=>row.addEventListener('click',()=>{const open=row.dataset.category==='travel';document.querySelectorAll('.category-row').forEach(item=>{item.classList.toggle('active',item===row);item.querySelector('b').textContent=item===row?'−':'+'});document.querySelector('#travel-panel').hidden=!open}));
const places={hawaii:['Hawaii','Light, water, and island rhythm.'],tibet:['Tibet','Ritual, color, and life at altitude.'],beijing:['Beijing','Old geometry in a changing city.'],seattle:['Seattle','Rain, distance, and Northwest quiet.']};
const gallery=document.querySelector('#collection-gallery');if(gallery){const slug=new URLSearchParams(location.search).get('place')||'tibet';const [name,description]=places[slug]||places.tibet;document.title=`${name} — Aria Guo`;document.querySelector('#place-title').textContent=name;const intro=document.querySelector('#place-description');intro.textContent=description;intro.dataset.editKey=`${slug}-introduction`;bindEditable(intro,intro.dataset.editKey);for(let i=1;i<=6;i++){const card=document.createElement('article');card.className='gallery-card';card.innerHTML=flipMarkup(`${slug}-photo-${i}`,`${name} · ${String(i).padStart(2,'0')}`,true);gallery.appendChild(card)}activateFlips(gallery)}
document.querySelectorAll('#year').forEach(el=>el.textContent=new Date().getFullYear());
